### ISSUE TITLE
Translating japanese dosnt work

### ISSUE THREAD

**Issue by CommicKick69ing** [OneMoreGres/ScreenTranslator#6] opened 2019-07-12 01:32 UTC
I try to translate japanese but when ever I do it for some reason gives me a comprehensional mess. For example if when I translated this "動いていない" it gave me this "@ MA'CLWZCU" as a translation. Can anyone help me?

**Comment by OneMoreGres** [comment] 2019-07-12 16:56
Duplicate of #5 

In short, everything you can do now is:
* ensure text is property recognized (try several times)
* update translation scripts
* change translation providers

Comment in original issue pls.

**Closed by OneMoreGres** 2019-07-12 16:56 UTC

**Comment by CommicKick69ing** [comment] 2019-07-12 17:09
I did all that but it still dosnt work

**Comment by OneMoreGres** [comment] 2019-07-12 17:20
Currently there is nothing more you can do.
Wait for updates (someday), try alternatives or use a separate OCR tool and online translators.
