### ISSUE TITLE
Application error on exiting

### ISSUE THREAD

**Issue by arodi007** [OneMoreGres/ScreenTranslator#26] opened 2020-04-30 15:03 UTC
I get memory error when turning off windows and get the following error:
![Screenshot_1](https://user-images.githubusercontent.com/52275564/80726294-436ccf80-8b15-11ea-8e9e-d5ea6cc8150c.png)

Spec:
windows 10
RAM 16 GB

**Comment by OneMoreGres** [comment] 2020-04-30 19:47
What windows do you close (turn off?)?
Enable `write trace file` option in settings and post here (or email me) resulting log file after crash

**Comment by arodi007** [comment] 2020-05-01 07:38
[screen-translator-2020-05-01-11-35-00.zip](https://github.com/OneMoreGres/ScreenTranslator/files/4562904/screen-translator-2020-05-01-11-35-00.zip)

i mean turning off or restarting my pc, it seem it didnt catch the error from the log file.

**Comment by OneMoreGres** [comment] 2020-05-01 08:42
You start the pc, the start the app, then capture/recognize/translate some text, then hide the result window(s), then shut down the pc and during the shutdown process this error occurs? Where I'm wrong?
Does it shows the error on every shutdown? And if you do not capture anything?

**Comment by arodi007** [comment] 2020-05-01 11:13
-start pc
-start the app
- restart or shut down pc, error always pop-up 
i can cancel the shut down, that how i screenshot the error msg.

**Comment by arodi007** [comment] 2020-05-01 13:39
i either get brkpt error or memory:
![Screenshot_3](https://user-images.githubusercontent.com/52275564/80809355-8b056100-8bd2-11ea-833e-9cdb83fe1659.png)

here the log file:
[screen-translator-2020-05-01-17-36-11.zip](https://github.com/OneMoreGres/ScreenTranslator/files/4564417/screen-translator-2020-05-01-17-36-11.zip)

**Comment by OneMoreGres** [comment] 2020-05-01 14:20
Since I can't reproduce this error and you're the only one encountered this issue so far, maybe it's a system specific. Maybe translator is being blocked by antivirus, maybe your pc have some hardware issues (disk/RAM/overclock), maybe your windows installation is corrupt (registry/some system files). Try uninstalling previous translator's version if you have one or run some system check/repair tools.

**Comment by OneMoreGres** [comment] 2020-05-09 11:03
Closing the issue. Comment if you have some other insights.
If someone else have this issue, post some details here too, please.

**Closed by OneMoreGres** 2020-05-09 11:03 UTC
